[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["cd cdp-lite && npm install"]

[phases.build]
cmds = ["cd cdp-lite/frontend && npm run build"]

[start]
cmd = "cd cdp-lite && npm start"